//! The exe's sound slots: the file each slot ends up holding after the start-up loader has run (a slot loaded twice keeps
//! the later file). Paths are relative to the game's Sounds folder, or under "simsfx/" for the SimsFX folder.

/// (slot, file); None where the exe loads a path that does not exist, so nothing plays.
pub const SLOTS: &[(i32, Option<&str>)] = &[
    (0, Some("Golf sfx/Drive With Ball.wav")),
    (1, Some("Golf sfx/Iron.wav")),
    (2, Some("Golf sfx/Chip.wav")),
    (3, Some("Golf sfx/Putt.wav")),
    (4, Some("Golf sfx/Ball In Hole.wav")),
    (5, Some("Golf sfx/Ball Water.wav")),
    (6, Some("Golf sfx/Ball Tree.wav")),
    (7, Some("Golf sfx/Ball Tree2.wav")),
    (8, Some("simsfx/Female/fWATER0.wav")),
    (9, Some("simsfx/Male/mWATER0.wav")),
    (10, Some("simsfx/Female/fHAPPY0.wav")),
    (11, Some("simsfx/Male/mHAPPY0.wav")),
    (12, Some("simsfx/Female/fHAPPY1.wav")),
    (13, Some("simsfx/Male/mHAPPY1.wav")),
    (14, Some("Female/Good Shot FM2.wav")),
    (15, Some("Male/Good Shot M2.wav")),
    (16, Some("emotion/PLS Failure mix.wav")),
    (17, Some("emotion/MKLS Failure mix.wav")),
    (18, Some("emotion/MalePSSFailure.wav")),
    (19, Some("emotion/SSS Failure mix.wav")),
    (20, Some("simsfx/Female/fTRICKY0.wav")),
    (21, Some("emotion/FemalePLSFailure.wav")),
    (22, Some("emotion/FemaleSSSFailure.wav")),
    (23, Some("emotion/FemalePSSFailure.wav")),
    (24, Some("emotion/FemaleSkTTFailure.wav")),
    (25, Some("effects/cash.wav")),
    (29, Some("effects/lake 1.wav")),
    (30, Some("effects/wind 1.wav")),
    (31, Some("effects/desert3.wav")),
    (32, Some("effects/forest2.wav")),
    (33, Some("effects/grass3.wav")),
    (34, Some("effects/fly.wav")),
    (35, Some("effects/taunt009.wav")),
    (36, Some("effects/unrest 2.wav")),
    (37, Some("effects/twinkle.wav")),
    (38, Some("effects/TimeTunnelClip2.wav")),
    (39, Some("effects/winter.wav")),
    (40, Some("effects/spring.wav")),
    (41, Some("effects/belch.wav")),
    (42, Some("effects/tada.wav")),
    (43, Some("effects/tada 2.wav")),
    (44, Some("buy2short.wav")),
    (45, Some("GolfAmbience122.wav")),
    (46, Some("Applause.wav")),
    (47, Some("ApplauseGood.wav")),
    (48, Some("ApplauseBad.wav")),
    (49, Some("golf sfx/Cart Away.wav")),
    (50, Some("buy1short.wav")),
    (51, Some("buy3short.wav")),
    (52, Some("buy4short.wav")),
    (53, Some("Romeo and Juliet Edit.wav")),
    (54, Some("Golf sfx/Ball Drop Fairway.wav")),
    (55, Some("Golf sfx/Ball Drop Sand.wav")),
    (56, Some("effects/tada 3.wav")),
    (57, Some("effects/Hot Air Long.wav")),
    (58, Some("effects/Seriama Amazon.wav")),
    (59, Some("effects/Moose 2.wav")),
    (60, Some("simsfx/Female/fCOKE0.wav")),
    (61, Some("simsfx/Male/mCOKE0.wav")),
    (62, Some("simsfx/Female/fBAD0.wav")),
    (63, Some("simsfx/Male/mBAD0.wav")),
    (64, Some("simsfx/Female/fSAD2.wav")),
    (65, Some("simsfx/Male/mSAD2.wav")),
    (66, Some("simsfx/Female/fCRAB0.wav")),
    (67, Some("simsfx/Male/mCRAB0.wav")),
    (68, Some("simsfx/Female/fWAITING0.wav")),
    (69, Some("simsfx/Male/mWAITING0.wav")),
    (70, Some("simsfx/Female/fMAD0.wav")),
    (71, Some("simsfx/Male/mMAD0.wav")),
    (72, Some("simsfx/Female/fBENCH0.wav")),
    (73, Some("simsfx/Male/mBENCH0.wav")),
    (74, Some("simsfx/Female/fSENIC0.wav")),
    (75, Some("simsfx/Male/mSENIC0.wav")),
    (76, Some("simsfx/Female/fLOVELY0.wav")),
    (77, Some("simsfx/Male/mLOVELY0.wav")),
    (78, Some("simsfx/Female/fCELEB0.wav")),
    (79, Some("simsfx/Male/mCELEB0.wav")),
    (80, Some("simsfx/Female/fWET0.wav")),
    (81, Some("simsfx/Male/mWET0.wav")),
    (82, Some("simsfx/Female/fOOPS0.wav")),
    (83, Some("simsfx/Male/mOOPS0.wav")),
    (86, Some("simsfx/Female/fUGLY0.wav")),
    (87, Some("simsfx/Male/mUGLY0.wav")),
    (88, Some("simsfx/Female/fSTORY0.wav")),
    (89, Some("simsfx/Male/mSTORY0.wav")),
    (90, Some("simsfx/Female/fSTORYNO.wav")),
    (91, Some("simsfx/Male/mSTORYNO.wav")),
    (92, Some("simsfx/Male/mGREETING.wav")),
    (93, Some("Celebs/Ranger.wav")),
    (94, Some("simsfx/Male/mCRABGRASS2.wav")),
    (95, Some("Celebs/Tray girl.wav")),
    (96, None),
    (97, Some("Celebs/Marshal Male.wav")),
    (98, Some("Celebs/Lawn Technician.wav")),
    (99, Some("simsfx/Female/fHAVEADRINK.wav")),
    (100, Some("Celebs/mGREETING.wav")),
    (101, Some("Celebs/Politician Dislike.wav")),
    (102, Some("Celebs/Action Star Dislike.wav")),
    (103, Some("Celebs/Politician Like.wav")),
    (104, Some("Celebs/Spears Like.wav")),
    (105, Some("Celebs/Spears Dislike.wav")),
    (106, Some("Celebs/Fitness Female.wav")),
    (107, Some("Celebs/Tray Girl.wav")),
    (110, Some("world/Steel Drums 2.wav")),
    (111, Some("music/Tropical Music/Steel Drum 1a.wav")),
    (112, Some("music/Tropical Music/Steel Drums 3.wav")),
    (115, Some("world/Bagpipe.wav")),
    (116, Some("music/Links Music/Harpiscord 1.wav")),
    (117, Some("music/Links Music/Bagpipe2.wav")),
    (120, Some("world/Spanish Guitar wFlute 2.wav")),
    (121, Some("music/Desert Music/Spanish Guitar 1.wav")),
    (122, Some("music/Desert Music/Spanish Guitar 3.wav")),
    (125, Some("New Age.wav")),
    (126, Some("Golf Harp 7.wav")),
    (127, Some("Golf Harp 6.wav")),
    (128, Some("Music Idea.wav")),
    (129, Some("music/credit.wav")),
    (130, Some("celebs/I'll Be Back.wav")),
    (131, Some("celebs/Spears Char.wav")),
    (132, Some("celebs/Politician Char.wav")),
    (133, Some("celebs/Comedian Char.wav")),
    (134, Some("celebs/Super Model.wav")),
    (135, Some("celebs/Fitness Female.wav")),
    (136, Some("celebs/Female Comic.wav")),
    (137, Some("simsfx/male/Vox_clear_throat_M3.wav")),
    (138, Some("celebs/Movie Princess.wav")),
    (139, Some("celebs/Rock Star.wav")),
    (140, Some("celebs/Basketball.wav")),
    (141, Some("celebs/Aging Star.wav")),
    (143, Some("interface/violin down 2.wav")),
    (144, Some("effects/club 2 drop no wtr.wav")),
    (145, Some("effects/tree sprout 3.wav")),
    (146, Some("effects/palm.wav")),
    (147, Some("effects/maple.wav")),
    (148, Some("effects/flower bed.wav")),
    (149, Some("effects/camera.wav")),
    (150, Some("simsfx/female/fVARIETY.wav")),
    (151, Some("simsfx/Male/mVARIETY.wav")),
    (152, Some("simsfx/female/fSAME.wav")),
    (153, Some("simsfx/Male/mSAME.wav")),
    (154, Some("simsfx/female/fBADHOLE.wav")),
    (155, Some("simsfx/Male/mBADHOLE.wav")),
    (156, Some("simsfx/female/fHUNGRY.wav")),
    (157, Some("simsfx/Male/mHUNGRY.wav")),
    (158, Some("simsfx/female/fTHIRSTY.wav")),
    (159, Some("simsfx/Male/mTHIRSTY.wav")),
    (160, Some("simsfx/female/fTIRED.wav")),
    (161, Some("simsfx/Male/mTIRED.wav")),
    (162, Some("simsfx/female/fOPTIONS.wav")),
    (163, Some("simsfx/Male/mOPTIONS.wav")),
    (164, Some("simsfx/Female/fSTORYOK.wav")),
    (165, Some("simsfx/Male/mSTORYOK.wav")),
    (166, Some("simsfx/Female/fSTORYYES.wav")),
    (167, Some("simsfx/Male/mSTORYYES.wav")),
    (188, Some("Golf sfx/Tiger Bounce 3.wav")),
    (189, Some("Golf sfx/Tiger Swing 1.wav")),
    (190, Some("Golf sfx/Golf Swing Perfect M.wav")),
    (191, Some("Golf sfx/Golf Swing NoAcc.wav")),
    (192, Some("Golf sfx/Golf Swing NoImag M.wav")),
    (193, Some("Golf sfx/Golf Swing Perfect FM.wav")),
    (194, Some("shotgun.wav")),
    (195, Some("effects/Sheep 1.wav")),
    (196, Some("effects/Alligator.wav")),
    (197, Some("effects/gila monster.wav")),
    (198, Some("effects/snake.wav")),
    (199, Some("interface/bass up 2.wav")),
    (200, Some("interface/bass down 2.wav")),
    (209, Some("Sail Boat.wav")),
    (210, Some("emotion/PLS Happy mix.wav")),
    (211, Some("emotion/MKLS Happy Mix.wav")),
    (212, Some("emotion/MalePSSHappy.wav")),
    (213, Some("emotion/SSS Happy mix.wav")),
    (215, Some("emotion/FemalePLSHappy.wav")),
    (216, Some("emotion/FemaleSSSHappy.wav")),
    (217, Some("emotion/FemalePSSHappy.wav")),
    (218, Some("emotion/FemaleSkTTHappy.wav")),
    (220, Some("emotion/PLS Sid mix.wav")),
    (221, Some("emotion/MKLS Sad mix.wav")),
    (222, Some("emotion/MalePSSSad.wav")),
    (223, Some("emotion/SSS Sad mix.wav")),
    (225, Some("emotion/FemalePLSSad.wav")),
    (226, Some("emotion/FemaleSSSSad.wav")),
    (227, Some("emotion/FemalePSSSad.wav")),
    (228, Some("emotion/FemaleSkTTSad.wav")),
    (230, Some("emotion/PLS Success mix.wav")),
    (231, Some("emotion/MKLS Success mix.wav")),
    (232, Some("emotion/MalePSSSuccess.wav")),
    (233, Some("emotion/SSS Success mix.wav")),
    (235, Some("emotion/FemalePLSSuccess.wav")),
    (236, Some("emotion/FemaleSSSSuccess.wav")),
    (237, Some("emotion/FemalePSSSuccess.wav")),
    (238, Some("emotion/FemaleSkTTSuccess.wav")),
    (250, Some("interface/button1.wav")),
    (251, Some("interface/button2.wav")),
    (252, Some("interface/button3.wav")),
    (255, Some("interface/building.wav")),
    (256, Some("interface/test 9.wav")),
    (257, Some("interface/test 7.wav")),
    (258, Some("interface/place rocks 1.wav")),
    (259, Some("interface/place water.wav")),
    (260, Some("interface/test 10.wav")),
    (261, Some("interface/test 2.wav")),
    (262, Some("interface/bench.wav")),
    (263, Some("interface/bridge.wav")),
    (264, Some("interface/path.wav")),
    (265, Some("interface/check box.wav")),
    (266, Some("interface/text box.wav")),
    (267, Some("interface/slide pop up.wav")),
    (268, Some("interface/unavailable.wav")),
    (269, Some("interface/wrong.wav")),
];

/// File held by a sound slot.
pub fn slot_file(slot: i32) -> Option<&'static str> {
    SLOTS.iter().find(|s| s.0 == slot).and_then(|s| s.1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_slots() {
        assert_eq!(slot_file(190), Some("Golf sfx/Golf Swing Perfect M.wav"));
        assert_eq!(slot_file(4), Some("Golf sfx/Ball In Hole.wav"));
        assert_eq!(slot_file(96), None);
    }
}
